#!/usr/bin/env bash
set -Eeuo pipefail
case "$-" in *x*) set +x ;; esac
die(){ printf 'ERROR: %s\n' "$*" >&2; exit 1; }
usage(){ printf '%s\n' 'Usage: rds-read-only-preflight.sh --ec2-instance-id i-... --vpc-id vpc-... --subnet-id subnet-... --subnet-id subnet-... --ec2-security-group-id sg-... [--rds-security-group-id sg-...] [--region ap-northeast-2]'; }
REGION=ap-northeast-2; INSTANCE= VPC= EC2_SG= RDS_SG=; SUBNETS=(); declare -A seen=()
while (($#)); do case "$1" in --subnet-id) [[ $# -gt 1 && -n "$2" && "$2" != --* ]] || die 'missing value for --subnet-id'; SUBNETS+=("$2"); shift 2;; --ec2-instance-id|--vpc-id|--ec2-security-group-id|--rds-security-group-id|--region) [[ -z "${seen[$1]:-}" && $# -gt 1 && -n "$2" && "$2" != --* ]] || die "duplicate or missing value for $1"; seen[$1]=1; case "$1" in --ec2-instance-id) INSTANCE=$2;; --vpc-id) VPC=$2;; --ec2-security-group-id) EC2_SG=$2;; --rds-security-group-id) RDS_SG=$2;; --region) REGION=$2;; esac; shift 2;; --help) usage; exit 0;; *) usage >&2; die "unknown argument: $1";; esac; done
[[ "$REGION" == ap-northeast-2 ]] || die 'approved region is ap-northeast-2'
[[ "$INSTANCE" =~ ^i-[0-9a-f]{8,17}$ && "$VPC" =~ ^vpc-[0-9a-f]{8,17}$ && "$EC2_SG" =~ ^sg-[0-9a-f]{8,17}$ ]] || die 'AWS resource identifier shape is invalid'
if [[ -n "$RDS_SG" ]]; then [[ "$RDS_SG" =~ ^sg-[0-9a-f]{8,17}$ ]] || die 'RDS security group identifier shape is invalid'; fi
(( ${#SUBNETS[@]} >= 2 )) || die 'at least two subnet IDs are required'; declare -A wanted=(); for s in "${SUBNETS[@]}"; do [[ "$s" =~ ^subnet-[0-9a-f]{8,17}$ && -z "${wanted[$s]:-}" ]] || die 'subnet IDs must be unique and valid'; wanted[$s]=1; done
command -v aws >/dev/null || die 'AWS CLI is required'
aws_ro(){ case "$1:$2" in ec2:describe-instances|ec2:describe-vpcs|ec2:describe-subnets|ec2:describe-security-groups|rds:describe-orderable-db-instance-options) ;; *) die 'AWS mutation or unsupported operation is forbidden';; esac; aws "$@"; }
AZ="$(aws_ro ec2 describe-instances --region "$REGION" --instance-ids "$INSTANCE" --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --output text)" || die 'EC2 AZ describe failed'
ACTUAL_VPC="$(aws_ro ec2 describe-instances --region "$REGION" --instance-ids "$INSTANCE" --query 'Reservations[0].Instances[0].VpcId' --output text)" || die 'EC2 VPC describe failed'
STATE="$(aws_ro ec2 describe-instances --region "$REGION" --instance-ids "$INSTANCE" --query 'Reservations[0].Instances[0].State.Name' --output text)" || die 'EC2 state describe failed'
groups=" $(aws_ro ec2 describe-instances --region "$REGION" --instance-ids "$INSTANCE" --query 'Reservations[0].Instances[0].SecurityGroups[].GroupId' --output text | tr '\t\n' '  ') " || die 'EC2 security group describe failed'
[[ "$AZ" == ap-northeast-2d && "$ACTUAL_VPC" == "$VPC" && "$STATE" == running ]] || die 'EC2 AZ, VPC, or running state does not meet the production contract'
[[ "$groups" == *" $EC2_SG "* ]] || die 'expected EC2 security group is not attached to the instance'
[[ "$(aws_ro ec2 describe-vpcs --region "$REGION" --vpc-ids "$VPC" --query 'Vpcs[0].State' --output text)" == available ]] || die 'VPC is not available'
subnets="$(aws_ro ec2 describe-subnets --region "$REGION" --subnet-ids "${SUBNETS[@]}" --query 'Subnets[].[SubnetId,VpcId,AvailabilityZone,State,AvailableIpAddressCount]' --output text)" || die 'subnet describe failed'
declare -A returned=() azs=(); while read -r subnet subnet_vpc subnet_az subnet_state available; do [[ -n "${wanted[$subnet]:-}" && "$subnet_vpc" == "$VPC" && "$subnet_state" == available && "$available" =~ ^[1-9][0-9]*$ ]] || die 'subnet response is missing, unusable, or outside the VPC'; returned[$subnet]=1; azs[$subnet_az]=1; done <<<"$(tr '\t' ' ' <<<"$subnets")"
[[ ${#returned[@]} == ${#wanted[@]} && -n "${azs[ap-northeast-2d]:-}" && ${#azs[@]} -ge 2 ]] || die 'subnets must exactly cover two or more AZs including ap-northeast-2d'
orderable="$(aws_ro rds describe-orderable-db-instance-options --region "$REGION" --engine mysql --db-instance-class db.t4g.micro --vpc --query 'OrderableDBInstanceOptions[].[Engine,EngineVersion,DBInstanceClass,StorageType,SupportsStorageEncryption,Vpc,MinStorageSize,MaxStorageSize]' --output text)" || die 'RDS orderability describe failed'
orderable_ok=false; while read -r engine version instance_class storage encrypted vpc min_storage max_storage; do if [[ "$engine" == mysql && "$version" =~ ^8\.4(\.[0-9]+)?$ && "$instance_class" == db.t4g.micro && "$storage" == gp3 && "$encrypted" == True && "$vpc" == True && "$min_storage" =~ ^[0-9]+$ && "$max_storage" =~ ^[0-9]+$ ]] && (( min_storage <= 20 && max_storage >= 20 )); then orderable_ok=true; fi; done <<<"$(tr '\t' ' ' <<<"$orderable")"; [[ "$orderable_ok" == true ]] || die 'MySQL 8.4 db.t4g.micro gp3 encrypted VPC orderability at 20 GiB is unavailable'
if [[ -n "$RDS_SG" ]]; then
  rds_sg_vpc="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'SecurityGroups[0].VpcId' --output text)" || die 'RDS security group VPC describe failed'; [[ "$rds_sg_vpc" == "$VPC" ]] || die 'RDS security group is not in the approved VPC'
  permission_count="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'length(SecurityGroups[0].IpPermissions)' --output text)" || die 'RDS security group permission count describe failed'; [[ "$permission_count" == 1 ]] || die 'RDS SG must contain exactly one ingress permission'
  proto="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'SecurityGroups[0].IpPermissions[0].IpProtocol' --output text)"; from="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'SecurityGroups[0].IpPermissions[0].FromPort' --output text)"; to="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'SecurityGroups[0].IpPermissions[0].ToPort' --output text)"; source_count="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'length(SecurityGroups[0].IpPermissions[0].UserIdGroupPairs)' --output text)"; source="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'SecurityGroups[0].IpPermissions[0].UserIdGroupPairs[0].GroupId' --output text)"; ipv4_count="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'length(SecurityGroups[0].IpPermissions[0].IpRanges)' --output text)"; ipv6_count="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'length(SecurityGroups[0].IpPermissions[0].Ipv6Ranges)' --output text)"; prefix_count="$(aws_ro ec2 describe-security-groups --region "$REGION" --group-ids "$RDS_SG" --query 'length(SecurityGroups[0].IpPermissions[0].PrefixListIds)' --output text)"
  [[ "$proto" == tcp && "$from" == 3306 && "$to" == 3306 && "$source_count" == 1 && "$source" == "$EC2_SG" && "$ipv4_count" == 0 && "$ipv6_count" == 0 && "$prefix_count" == 0 ]] || die 'RDS SG must reject all-protocol, ranges covering 3306, CIDR, IPv6, and prefix-list exposure'
  printf '%s\n' 'RDS read-only preflight passed: EC2/VPC/subnet/orderability/security-group contracts verified'
else
  printf '%s\n' 'RDS base read-only preflight passed: EC2/VPC/subnet/orderability contracts verified; RDS security-group validation remains pending'
fi
printf '%s\n' 'Creation-time REQUIRED: Single-AZ; PubliclyAccessible=false; StorageEncrypted=true; gp3 minimum 20 GiB; automated backup/PITR enabled; retention requires later cost and operation approval.'
