"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ErrorState, LoadingState } from "@/components/async-state";
import { ApiError, recommendationApi, type RecommendationItem } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { v2Api, type Pet } from "@/lib/v2-api";

export default function Home(){const auth=useAuth();return <div className="home-stack"><section className="home-hero"><div><p className="eyebrow">PawCycle commerce</p><h1>매일의 반려생활,<br/>더 편안하게 이어가요.</h1><p>필요한 상품을 찾고, 다음 배송을 관리하고, 우리 아이에게 맞는 일상용품을 골라보세요.</p><div className="button-row"><Link className="button button-primary" href="/products">상품 둘러보기</Link>{auth.status==="anonymous"?<Link className="button button-secondary" href="/login?returnTo=%2F">로그인</Link>:<Link className="button button-secondary" href="/subscriptions">내 정기배송</Link>}</div></div><aside className="hero-note"><strong>정기배송</strong><span>필요한 주기에 맞춰<br/>다음 배송을 관리하세요.</span><Link href="/subscriptions">자세히 보기 →</Link></aside></section>{auth.status==="loading"?<LoadingState>회원 정보를 확인하고 있습니다.</LoadingState>:null}{auth.status==="error"?<ErrorState title="로그인 상태를 확인할 수 없습니다." message={auth.errorMessage??"다시 시도해 주세요."} onRetry={()=>void auth.refresh()}/>:null}{auth.status==="authenticated"&&auth.memberId!==null?<PersonalizedRecommendations key={auth.memberId}/>:<GuestValue/>}<QuickActions/></div>;}
function GuestValue(){return <section className="feature-strip"><div><strong>필요한 것만, 쉽게</strong><span>공개 상품을 바로 탐색할 수 있어요.</span></div><div><strong>내 반려동물에 맞게</strong><span>로그인 후 직접 선택한 Pet으로 추천을 받아요.</span></div><div><strong>다음 배송을 한눈에</strong><span>정기배송을 시작하고 일정도 직접 관리해요.</span></div></section>;}
function QuickActions(){return <section className="quick-section"><div className="section-title"><div><p className="eyebrow">빠른 이동</p><h2>필요한 일을 바로 시작하세요</h2></div></div><div className="quick-grid"><Link href="/products"><strong>상품 탐색</strong><span>상품과 옵션을 찾아보세요</span></Link><Link href="/subscriptions"><strong>정기배송 관리</strong><span>다음 배송과 변경 사항을 확인해요</span></Link><Link href="/orders"><strong>주문 내역</strong><span>주문과 배송 상태를 확인해요</span></Link></div></section>}
function PersonalizedRecommendations(){const [pets,setPets]=useState<Pet[]|null>(null);const [petId,setPetId]=useState("");const [items,setItems]=useState<RecommendationItem[]|null>(null);const [error,setError]=useState<string|null>(null);const [petError,setPetError]=useState<string|null>(null);const [retry,setRetry]=useState(0);const request=useRef(0);useEffect(()=>{let active=true;void v2Api.pets.list().then(({body})=>{if(active)setPets(body.items);}).catch(()=>{if(active)setPetError("반려동물 목록을 불러오지 못했습니다.");});return()=>{active=false;request.current+=1;};},[retry]);async function load(){if(!petId)return;const id=++request.current;setError(null);setItems(null);try{const result=await recommendationApi.products(Number(petId));if(request.current===id)setItems(result.products);}catch(e){if(request.current===id)setError(e instanceof ApiError&&e.code==="PET_NOT_FOUND"?"선택한 반려동물을 찾을 수 없습니다. 다시 선택해 주세요.":"추천을 불러오지 못했습니다.");}}return <section className="recommendation-section"><div className="section-title"><div><p className="eyebrow">맞춤 추천</p><h2>우리 아이에게 맞는 상품을 찾아볼까요?</h2><p>반려동물을 직접 선택하면 현재 판매 중인 상품을 추천해 드려요.</p></div></div>{petError?<ErrorState title="반려동물 목록을 불러오지 못했습니다." message={petError} onRetry={()=>{setPets(null);setPetError(null);setRetry(v=>v+1);}}/>:pets===null?<LoadingState>반려동물 목록을 불러오고 있습니다.</LoadingState>:pets.length===0?<div className="empty-callout"><strong>등록된 반려동물이 없습니다.</strong><Link href="/subscriptions/new">반려동물 등록하고 정기배송 시작하기</Link></div>:<><div className="recommendation-controls"><label className="form-field">반려동물 선택<select className="input" value={petId} onChange={e=>{request.current+=1;setPetId(e.target.value);setItems(null);setError(null);}}><option value="">선택하세요</option>{pets.map(p=><option key={p.petId} value={p.petId}>{p.name} · {p.petType}</option>)}</select></label><button className="button button-primary" type="button" disabled={!petId} onClick={()=>void load()}>추천 보기</button></div>{error?<ErrorState title="추천을 불러오지 못했습니다." message={error} onRetry={()=>void load()}/>:null}{items?.length===0?<div className="empty-callout">현재 추천 가능한 상품이 없습니다.</div>:items?<div className="recommendation-grid">{items.map(item=><Link className="recommendation-card" key={item.productId} href={`/products/${item.productId}`}>{item.thumbnailUrl?<img src={item.thumbnailUrl} alt=""/>:<span className="image-placeholder">PawCycle</span>}<div><span className="tag">{item.category.name}</span><h3>{item.name}</h3><p>{item.reason}</p><span className="card-link">상품 보기 →</span></div></Link>)}</div>:null}</>}</section>;}
