"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ErrorState, LoadingState } from "./async-state";
import { ApiError, type ProductDetail, productApi } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { commerceFinalApi } from "@/lib/commerce-final-api";
import { buildLoginHref, formatPetType, formatPrice } from "@/lib/frontend-utils";

type ProductState = { status:"loading" } | { status:"success"; product:ProductDetail } | { status:"not-found" } | { status:"error"; message:string };
export const CANONICAL_SUBSCRIPTION_START_HREF = "/subscriptions/new";

export function ProductDetailScreen({ productId }:{productId:string}) {
  const auth=useAuth(); const [state,setState]=useState<ProductState>({status:"loading"}); const [retry,setRetry]=useState(0);
  const [cartSkuId,setCartSkuId]=useState<number|null>(null); const [quantity,setQuantity]=useState("1"); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null); const [messageKind,setMessageKind]=useState<"success"|"error">("error");
  useEffect(()=>{let active=true;void productApi.detail(productId).then(product=>{if(active)setState({status:"success",product});}).catch((error:unknown)=>{if(!active)return;if(error instanceof ApiError&&error.code==="PRODUCT_NOT_FOUND")setState({status:"not-found"});else setState({status:"error",message:error instanceof ApiError?error.message:"상품 정보를 불러오지 못했습니다."});});return()=>{active=false;};},[productId,retry]);
  const product=state.status==="success"?state.product:null;
  function canMutate(){if(auth.status==="anonymous"&&product){setMessageKind("error");location.assign(buildLoginHref(`/products/${product.productId}`));return false;}if(auth.status!=="authenticated"){setMessageKind("error");setMessage(auth.status==="loading"?"로그인 상태를 확인하고 있습니다. 잠시 후 다시 시도해 주세요.":"로그인 상태를 확인하지 못했습니다. 다시 확인한 뒤 시도해 주세요.");return false;}return true;}
  async function addWishlist(){if(!product||busy||!canMutate())return;setBusy(true);setMessage(null);try{await auth.executeWithCsrf(csrf=>commerceFinalApi.addWishlist(product.productId,csrf));setMessageKind("success");setMessage("위시리스트에 담았습니다.");}catch(error){setMessageKind("error");setMessage(error instanceof ApiError?error.message:"위시리스트에 담지 못했습니다.");}finally{setBusy(false);}}
  async function addCart(){if(!product||!cartSkuId||busy){setMessageKind("error");setMessage("일반 구매 옵션을 선택해 주세요.");return;}if(!canMutate())return;const parsed=Number(quantity);if(!Number.isInteger(parsed)||parsed<1){setMessageKind("error");setMessage("수량을 확인해 주세요.");return;}setBusy(true);setMessage(null);try{await auth.executeWithCsrf(csrf=>commerceFinalApi.addCart(cartSkuId,parsed,csrf));setMessageKind("success");setMessage("장바구니에 담았습니다.");}catch(error){setMessageKind("error");setMessage(error instanceof ApiError?error.message:"장바구니에 담지 못했습니다.");}finally{setBusy(false);}}
  if(state.status==="loading")return <LoadingState>상품 정보를 불러오고 있습니다.</LoadingState>;
  if(state.status==="not-found")return <ErrorState title="상품을 확인할 수 없습니다." message="존재하지 않거나 공개되지 않은 상품입니다."><Link className="button button-secondary" href="/products">상품 목록으로</Link></ErrorState>;
  if(state.status==="error")return <ErrorState title="상품을 불러오지 못했습니다." message={state.message} onRetry={()=>{setState({status:"loading"});setRetry(value=>value+1);}}><Link className="button button-secondary" href="/products">상품 목록으로</Link></ErrorState>;
  return <><Link className="breadcrumb" href="/products">← 상품 목록</Link><div className="product-detail-layout"><section className="product-gallery">{product!.thumbnailUrl?<img className="product-hero-image" src={product!.thumbnailUrl} alt=""/>:<span className="image-placeholder">PawCycle</span>}</section><div className="product-purchase-stack"><section className="product-summary"><div className="card-meta"><span className="tag">{formatPetType(product!.petType)}</span><span className="tag">{product!.category.name}</span></div><h1>{product!.name}</h1><p className="description">{product!.description??"상세 설명이 준비되지 않았습니다."}</p></section><section className="purchase-panel"><div className="section-title"><div><p className="eyebrow">일반 구매</p><h2>옵션과 수량 선택</h2></div></div>{message?<p className={messageKind==="success"?"notice-success":"error-summary"} role={messageKind==="success"?"status":"alert"}>{message}</p>:null}<label className="form-field">상품 옵션<select className="input" value={cartSkuId??""} onChange={event=>setCartSkuId(Number(event.target.value)||null)}><option value="">선택하세요</option>{product!.skus.map(sku=><option key={sku.skuId} value={sku.skuId}>{sku.skuName} · {formatPrice(sku.price)}</option>)}</select></label><label className="form-field">수량<input className="input" type="number" min="1" value={quantity} onChange={event=>setQuantity(event.target.value)}/></label><div className="button-row"><button className="button button-secondary" type="button" disabled={busy} onClick={()=>void addWishlist()}>위시리스트에 담기</button><button className="button button-primary" type="button" disabled={busy||cartSkuId===null} onClick={()=>void addCart()}>장바구니에 담기</button></div></section><section className="subscription-entry"><div><strong>정기배송으로 더 편하게</strong><p>{product!.skus.some(sku=>sku.subscribable)?"반려동물과 플랜을 고른 뒤 원하는 주기로 받아보세요.":"현재 정기배송 가능한 옵션이 없습니다."}</p></div>{product!.skus.some(sku=>sku.subscribable)?<Link className="button button-secondary" href={CANONICAL_SUBSCRIPTION_START_HREF}>정기배송 시작</Link>:null}</section></div></div></>;
}
