"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ErrorState, LoadingState } from "@/components/async-state";
import { ApiError } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { buildLoginHref } from "@/lib/frontend-utils";
import { commerceFinalApi, type BillingMethodStatus } from "@/lib/commerce-final-api";
export default function BillingMethodsPage(){const auth=useAuth();const [status,setStatus]=useState<BillingMethodStatus|null>(null);const [error,setError]=useState<string|null>(null);const [prepared,setPrepared]=useState(false);const [busy,setBusy]=useState(false);const load=()=>{void commerceFinalApi.billingMethod().then((result)=>{setStatus(result);setError(null);}).catch((e:unknown)=>{if(e instanceof ApiError&&e.code==="AUTH_REQUIRED"){auth.markAnonymous();return;}setError(e instanceof ApiError?e.message:"결제수단 정보를 불러오지 못했습니다.");});};useEffect(()=>{if(auth.status==="authenticated")load();},[auth.status]);async function prepare(){if(busy||!status?.configured)return;setBusy(true);try{await auth.executeWithCsrf(csrf=>commerceFinalApi.prepareBilling(csrf));setPrepared(true);}catch(e){setError(e instanceof ApiError?e.message:"등록 준비를 시작하지 못했습니다.");}finally{setBusy(false);}}if(auth.status==="anonymous")return <ErrorState title="로그인이 필요합니다." message="결제수단을 보려면 로그인해 주세요."><Link className="button button-primary" href={buildLoginHref("/billing-methods")}>로그인</Link></ErrorState>;if(auth.status==="error")return <ErrorState title="로그인 상태를 확인할 수 없습니다." message={auth.errorMessage??"다시 시도해 주세요."} onRetry={()=>void auth.refresh()}/>;if(status===null&&!error)return <LoadingState>결제수단 정보를 불러오고 있습니다.</LoadingState>;if(status===null)return <ErrorState title="결제수단 정보를 불러오지 못했습니다." message={error??"다시 시도해 주세요."} onRetry={load}/>;return <section className="section-card"><h1>결제수단</h1><p>{status.registered?"등록된 결제수단이 있습니다.":"등록된 결제수단이 없습니다."}</p>{!status.configured?<p className="field-help">현재 환경에서는 결제 Provider가 구성되지 않았습니다.</p>:null}{error?<p className="field-error" role="alert">{error}</p>:null}<button className="button button-primary" type="button" disabled={busy||prepared||!status.configured} onClick={()=>void prepare()}>{busy?"준비 중":"결제수단 등록 준비"}</button>{prepared?<p className="field-help">등록 준비가 완료되었습니다. Toss 브라우저에서 authKey를 얻는 Client Provider 계약과 SDK가 현재 승인 범위에 없어 실제 등록 완료 단계는 지원하지 않습니다.</p>:null}</section>;}
