"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ErrorState, LoadingState } from "@/components/async-state";
import { ApiError } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { buildLoginHref, formatPrice } from "@/lib/frontend-utils";
import { commerceFinalApi, type Address, type CartItem, type CheckoutResult } from "@/lib/commerce-final-api";
import { newIdempotencyKey } from "@/lib/v2-api";
export default function CheckoutPage(){const auth=useAuth();const [cart,setCart]=useState<CartItem[]|null>(null);const [addresses,setAddresses]=useState<Address[]|null>(null);const [addressId,setAddressId]=useState<number|null>(null);const [result,setResult]=useState<CheckoutResult|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const key=useRef<string|null>(null);useEffect(()=>{if(auth.status!=="authenticated")return;void Promise.all([commerceFinalApi.cart(),commerceFinalApi.addresses()]).then(([c,a])=>{setCart(c.items);setAddresses(a);setAddressId(a.find(x=>x.isDefault)?.addressId??a[0]?.addressId??null);}).catch((e:unknown)=>setError(e instanceof ApiError?e.message:"결제 정보를 불러오지 못했습니다."));},[auth.status]);async function checkout(){if(!addressId||busy)return;setBusy(true);try{key.current??=newIdempotencyKey();setResult(await auth.executeWithCsrf(csrf=>commerceFinalApi.checkout(addressId,csrf,key.current!)));}catch(e){setError(e instanceof ApiError?e.message:"주문을 만들지 못했습니다.");}finally{setBusy(false);}}if(auth.status==="anonymous")return <ErrorState title="로그인이 필요합니다." message="주문하려면 로그인해 주세요."><Link className="button button-primary" href={buildLoginHref("/checkout")}>로그인</Link></ErrorState>;if(!cart||!addresses)return <LoadingState>주문 정보를 불러오고 있습니다.</LoadingState>;if(result)return <section className="section-card"><h1>주문이 생성되었습니다</h1><p>{result.orderName} · {formatPrice(result.amount)}</p><p>주문 번호: {result.orderNumber}</p><p className="field-help">결제 Provider 브라우저 계약은 현재 저장소에 없어 결제 인증 단계는 진행할 수 없습니다.</p><Link className="button button-primary" href={`/orders/${result.orderId}`}>주문 확인</Link></section>;return <section className="section-card"><h1>주문 확인</h1>{error?<p className="field-error" role="alert">{error}</p>:null}{cart.length?<ul className="history-list">{cart.map(i=><li key={i.skuId}><strong>{i.productName}</strong><span>{i.skuName} · {i.quantity}개 · {formatPrice(i.price)}</span></li>)}</ul>:<p>장바구니가 비어 있습니다.</p>}<label className="form-field">배송지<select className="input" value={addressId??""} onChange={e=>setAddressId(Number(e.target.value))}><option value="">배송지를 선택하세요</option>{addresses.map(a=><option key={a.addressId} value={a.addressId}>{a.name||a.recipientName} · {a.addressLine1}</option>)}</select></label>{!addresses.length?<Link className="button button-secondary" href="/addresses">배송지 등록</Link>:null}<button className="button button-primary" type="button" disabled={!cart.length||!addressId||busy} onClick={()=>void checkout()}>{busy?"주문 생성 중":"주문 생성"}</button></section>;}
