// Disposable, loopback-only visual QA. Never forwards API traffic to any backend.
import http from 'node:http';
const page = items => ({items,page:0,size:20,totalElements:items.length,totalPages:items.length ? 1 : 0});
const categories = ['사료','간식','위생·배변','목욕·케어'].map((name,i)=>({categoryId:i+1,name,slug:['food','treats','hygiene','care'][i],displayOrder:i,children:[]}));
const names=['데일리 어덜트 강아지 사료 2.5kg','동결건조 닭가슴살 간식','무향 벤토나이트 고양이 모래 대용량 6kg','민감한 반려동물을 위한 데일리 샴푸','긴 상품 이름과 여러 규격을 함께 표시하는 카탈로그 내구성 검증 상품','이미지가 없는 고양이 간식'];
const products=names.map((name,i)=>({productId:i+1,name,petType:i===2 || i===5 ? 'CAT':'DOG',shortDescription:'로컬 시각 검증용 가상 상품',thumbnailUrl:i===5 ? null:`/__fixture-image/${i}`,category:categories[i%4],brand:{brandId:i+1,name:i===4?'긴 브랜드 이름이 한 줄에서 안전하게 생략되는지 검증하는 독립 브랜드':['Daily bowl','FRESH BITES','CAT STUDIO','Soft paws'][i%4],slug:`brand-${i}`,logoUrl:null},skuPriceSummary:{skuPrices:[{skuId:101+i,skuName:'기본 규격',price:32000-i*2000}]},representativePrice:32000-i*2000,compareAtPrice:i===1?34000:null,discountRate:i===1?12:null,averageRating:i%2?4.5:null,reviewCount:i%2?12:0,purchasable:i!==4,hasSubscribableSku:i%2===0}));
const pets=[{petId:1,name:'보리',petType:'DOG',breed:'믹스',weightKg:8,profileComplete:true},{petId:2,name:'나비',petType:'CAT',breed:null,weightKg:null,profileComplete:false}];
const plans=[{planId:1,planName:'데일리 사료 플랜',targetPetType:'DOG',planVersionId:11,packagePriceKrw:32000,items:[{skuId:101,quantity:1}],allowedDeliveryCycleWeeks:[2,4,8],sale:{onSale:true,startsOn:'2026-01-01',endsOn:null}},{planId:2,planName:'사료와 간식 플랜',targetPetType:'DOG',planVersionId:12,packagePriceKrw:46000,items:[{skuId:101,quantity:1},{skuId:102,quantity:1}],allowedDeliveryCycleWeeks:[4,8],sale:{onSale:true,startsOn:'2026-01-01',endsOn:null}}];
const snapshot={planVersionId:11,packagePriceKrw:32000,deliveryCycleWeeks:4,items:[{skuId:101,quantity:1}]};
const subscriptionItems=[{skuId:101,skuName:'2.5kg',productId:1,productName:names[0],thumbnailUrl:products[0].thumbnailUrl,quantity:1}];
const addresses=[{addressId:1,name:'집 · QA 예시',recipientName:'테스트 수령인',recipientPhone:'010-0000-0000',postalCode:'00000',addressLine1:'가상 배송지 (실제 주소 아님)',addressLine2:'로컬 검증 전용',isDefault:true}];
let state={auth:true,cart:true,status:'ACTIVE',error:false};
let cartItems=products.slice(0,2).map((p,i)=>({skuId:101+i,quantity:1,skuCode:`QA-${i}`,skuName:'기본 규격',price:p.representativePrice,unitPrice:p.representativePrice,lineAmount:p.representativePrice,productId:p.productId,productName:p.name,availableQuantity:10,purchasable:true}));
function cart(){const items=state.cart?cartItems:[];const amount=items.reduce((sum,item)=>sum+item.lineAmount,0);return {items,pricing:{originalAmount:amount,subtotalAmount:amount,discountAmount:0,shippingFee:items.length?3000:0,finalAmount:amount+(items.length?3000:0),paymentAmount:amount+(items.length?3000:0)},version:1};}
function subscription(){return {subscriptionId:1,pet:pets[0],status:state.status,version:1,currentSnapshot:snapshot,pendingSnapshot:{...snapshot,deliveryCycleWeeks:8},nextScheduledDate:state.status==='ACTIVE'?'2026-09-10':null,nextDelivery:state.status==='ACTIVE'?{scheduleId:1,scheduledDate:'2026-09-10',status:'SCHEDULED',...snapshot,deliveryCycleWeeks:8,items:subscriptionItems,addOns:[],addOnTotalKrw:0,orderTotalKrw:32000}:null,pendingChange:state.status==='ACTIVE'?{appliesOn:'2026-09-10',...snapshot,deliveryCycleWeeks:8,items:subscriptionItems}:null,issue:null,availableActions:state.status==='CANCELED'?[]:state.status==='PAUSED'?['RESUME','CANCEL','UPDATE_SHIPPING_ADDRESS']:['SKIP_NEXT','PAUSE','CANCEL','RESCHEDULE_NEXT','CHANGE_PLAN','CHANGE_DELIVERY_CYCLE','UPDATE_SHIPPING_ADDRESS'],schedules:page([{scheduleId:1,scheduledDate:'2026-09-10',status:'SCHEDULED',effectiveSnapshotId:1}]),commandHistory:page([{commandType:'CHANGE_DELIVERY_CYCLE',result:'SUCCESS',occurredAt:'2026-08-30T09:00:00+09:00'}])};}
const order={orderId:1,orderNumber:'QA-20260830-000001',source:'CART',status:'PAID',originalAmount:62000,discountAmount:0,shippingFee:3000,paymentAmount:65000,...addresses[0],createdAt:'2026-08-30T09:00:00+09:00',paidAt:'2026-08-30T09:01:00+09:00',items:cartItems.map(i=>({...i,productNameSnapshot:i.productName,skuNameSnapshot:i.skuName})),payment:{paymentId:1,type:'ONE_TIME',provider:'TOSS',status:'SUCCEEDED',amount:65000,attemptNo:1},delivery:{deliveryId:1,status:'PREPARING'},cancellation:null,return:null,refunds:[],availableActions:['REQUEST_CANCELLATION','REQUEST_RETURN']};
const server=http.createServer(async(req,res)=>{
 const url=new URL(req.url,'http://127.0.0.1:3006'); const path=url.pathname;
 const json=(body,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','ETag':'"1"'});res.end(JSON.stringify(body));};
 if(path==='/__fixture'){for(const [k,v]of url.searchParams) {if(k==='auth')state.auth=v!=='anonymous';if(k==='cart')state.cart=v!=='empty';if(k==='status')state.status=v;if(k==='error')state.error=v==='true';}res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(`<h1>FE-006 로컬 fixture 전용</h1><p>서버/API/결제 통합 검증이 아닌 합성 응답을 사용한 UI 검증입니다.</p>${['/','/products','/products?q=no-result','/products/1','/cart','/checkout','/login','/orders/1','/subscriptions/new','/subscriptions/1','/my','/wishlist','/compare?productId=1&productId=2','/pets','/addresses','/billing-methods','/notifications','/support'].map(p=>`<p><a href="${p}">${p}</a></p>`).join('')}<a href="/__fixture?auth=anonymous">비로그인</a> · <a href="/__fixture?auth=member">로그인 fixture</a> · <a href="/__fixture?cart=empty">빈 장바구니</a> · <a href="/__fixture?cart=full">채운 장바구니</a> · <a href="/__fixture?status=PAUSED">일시정지</a> · <a href="/__fixture?status=ACTIVE">진행 중</a>`);return;}
 if(path.startsWith('/__fixture-image/')){const i=Number(path.split('/').at(-1));const color=['#b72434','#e1b40c','#258475','#1f589b','#29282c'][i%5];res.writeHead(200,{'Content-Type':'image/svg+xml'});res.end(`<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" fill="#f3f0f7"/><rect x="${i%2?100:80}" y="55" width="${i%2?200:240}" height="290" rx="12" fill="${color}"/><rect x="110" y="140" width="180" height="125" fill="white"/><text x="200" y="185" text-anchor="middle" font-family="sans-serif" font-size="21" fill="#241c2e">CATALOG QA</text><text x="200" y="225" text-anchor="middle" font-family="sans-serif" font-size="14">Fixture only · ${i+1}</text></svg>`);return;}
 if(path.startsWith('/api/')){
  if(path==='/api/auth/me')return state.auth?json({memberId:1}):json({code:'AUTH_REQUIRED',message:'로그인이 필요합니다.',fieldErrors:[]},401);
  if(path==='/api/auth/csrf')return json({token:'local-fixture-not-a-secret'});
  if(req.method!=='GET') {if(path==='/api/auth/login'){state.auth=true;return json({memberId:1});} if(path==='/api/interactions')return json({}); if(path.startsWith('/api/cart/items/')){const id=Number(path.split('/').at(-1));if(req.method==='DELETE')cartItems=cartItems.filter(i=>i.skuId!==id);else{let body='';for await(const chunk of req)body+=chunk;const qty=JSON.parse(body).quantity;cartItems=cartItems.map(i=>i.skuId===id?{...i,quantity:qty,lineAmount:qty*i.unitPrice}:i);}return json({});} return json({code:'QA_MUTATION_BLOCKED',message:'로컬 visual fixture에서는 이 변경을 실행하지 않습니다.',fieldErrors:[]},409);}
  if(state.error && path==='/api/products')return json({code:'QA_ERROR',message:'로컬 조회 실패 예시',fieldErrors:[]},503);
  if(path==='/api/catalog/discovery')return json({categories,brands:products.map(p=>p.brand),categoryFacets:[]});
  if(path==='/api/products')return json(page(url.searchParams.get('q')==='no-result'?[]:products.filter(p=>!url.searchParams.get('petType')||p.petType===url.searchParams.get('petType'))));
  if(path==='/api/products/compare')return json({products:products.slice(0,2).map(p=>({...p,brand:p.brand.name,category:p.category.name,subscriptionEligible:p.hasSubscribableSku,facets:[]})),aiStatus:'UNAVAILABLE',aiSummary:null});
  if(/^\/api\/products\/\d+$/.test(path)){const p=products.find(p=>p.productId===Number(path.split('/').at(-1)));return json({...p,description:'로컬 fixture로 사진 비율과 긴 상품 정보, 옵션 및 가격 위계를 검증합니다.',images:p.thumbnailUrl?[{imageId:1,imageUrl:p.thumbnailUrl,altText:p.name,displayOrder:0,imageType:'PRIMARY'}]:[],optionGroups:[{optionGroupId:1,name:'용량',displayOrder:0,values:[{optionValueId:1,value:'2.5kg',displayOrder:0},{optionValueId:2,value:'5kg',displayOrder:1}]}],detailSections:[],trust:{averageRating:null,reviewCount:0,questionCount:0},skus:[1,2].map((n)=>({skuId:100+n,skuName:n===1?'2.5kg':'5kg',price:n===1?32000:58000,compareAtPrice:null,discountRate:null,selectedOptions:[{optionGroupId:1,groupName:'용량',optionValueId:n,value:n===1?'2.5kg':'5kg'}],subscribable:true,availableDeliveryCycles:[4,8],availableQuantity:10,purchasable:true}))});}
  if(path.endsWith('/reviews/me'))return json({code:'REVIEW_NOT_FOUND',message:'등록한 리뷰가 없습니다.',fieldErrors:[]},404);
  if(path.endsWith('/reviews/summary'))return json({status:'INSUFFICIENT_REVIEWS',summary:null});
  if(path.endsWith('/reviews')||path.endsWith('/questions'))return json(page([]));
  if(path==='/api/recommendations/reorder-timing')return json({items:[]});
  if(path.startsWith('/api/recommendations')||path.endsWith('/related')||path.endsWith('/complementary'))return json({requestId:'qa-local',products:path.includes('popular')?products.slice(0,4).map(p=>({...p,reason:'로컬 fixture 상품',strategy:'POPULAR'})):[]});
  if(path==='/api/cart')return json(cart());
  if(path==='/api/addresses')return json(addresses);
  if(path==='/api/coupons')return json([]);
  if(path==='/api/wishlist')return json({items:products.slice(0,2).map(p=>({productId:p.productId,productName:p.name,createdAt:'2026-08-30T09:00:00+09:00'}))});
  if(path==='/api/orders')return json([order]);
  if(path==='/api/orders/1')return json(order);
  if(path.endsWith('/subscription-options'))return json({orderId:1,options:plans.map(p=>({...p,matchingProductIds:[1],compatibleOwnedPetIds:[1]}))});
  if(path==='/api/pets')return json(page(pets));
  if(path==='/api/subscription-plans')return json(page(plans));
  if(path.startsWith('/api/subscription-plan-versions/'))return json(plans.find(p=>p.planVersionId===Number(path.split('/').at(-1)))??plans[0]);
  if(path==='/api/subscriptions')return json(page([subscription()]));
  if(path.endsWith('/cycle-suggestion'))return json({subscriptionId:1,currentDeliveryCycleWeeks:4,medianSuccessfulIntervalWeeks:4,allowedDeliveryCycleWeeks:[2,4,8],suggestion:null});
  if(path==='/api/subscriptions/1')return json(subscription());
  if(path==='/api/payment-methods/toss/billing')return json({provider:'TOSS',configured:false,registered:false});
  if(path==='/api/notifications')return json([]);
  return json({code:'QA_ENDPOINT_NOT_CONFIGURED',message:'이 fixture에 없는 조회입니다.',fieldErrors:[]},404);
 }
 const proxy=http.request({hostname:'127.0.0.1',port:3007,path:req.url,method:req.method,headers:{...req.headers,host:'localhost:3006'}},up=>{res.writeHead(up.statusCode,up.headers);up.pipe(res);});proxy.on('error',()=>{res.writeHead(502);res.end('Start Next on port 3007 first.');});req.pipe(proxy);
});
server.listen(3006,'127.0.0.1',()=>console.log('Visual fixture http://localhost:3006/__fixture (Next: 3007; no backend forwarding)'));
