apiVersion: 1

datasources:
  - name: PawCycle Prometheus
    uid: pawcycle-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
