package com.pawcycle.backend.commerce;

import java.sql.Timestamp;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.support.TransactionTemplate;

@Service
public class PaymentReconciliationService {
	private final JdbcTemplate jdbc; private final TransactionTemplate tx; private final TossPaymentAdapter provider; private final NotificationService notifications;
	public PaymentReconciliationService(JdbcTemplate jdbc,org.springframework.transaction.PlatformTransactionManager manager,TossPaymentAdapter provider,NotificationService notifications){this.jdbc=jdbc;this.tx=new TransactionTemplate(manager);this.provider=provider;this.notifications=notifications;}
	public Map<String,Object> reconcile(long id){if(!provider.isConfigured())throw new CommerceException(503,"PAYMENT_PROVIDER_UNAVAILABLE","Toss 결제 Provider가 현재 환경에 구성되지 않았습니다.");Map<String,Object> work=tx.execute(s->{Map<String,Object> row=one("SELECT id,status,provider_order_id,reconciliation_attempts FROM payments WHERE id=? FOR UPDATE",id);if(row==null)throw new CommerceException(404,"PAYMENT_NOT_FOUND","요청한 리소스를 찾을 수 없습니다.");if(!"UNKNOWN".equals(row.get("status")))throw new CommerceException(409,"PAYMENT_RECONCILIATION_NOT_ALLOWED","UNKNOWN 결제만 대사할 수 있습니다.");int a=((Number)row.get("reconciliation_attempts")).intValue();if(a>=10)throw new CommerceException(409,"PAYMENT_RECONCILIATION_EXHAUSTED","결제 대사 횟수를 초과했습니다.");jdbc.update("UPDATE payments SET reconciliation_attempts=?,last_reconciled_at=? WHERE id=?",a+1,Timestamp.from(Instant.now()),id);return row;});TossPaymentAdapter.ConfirmResult result=provider.queryPayment((String)work.get("provider_order_id"));return tx.execute(s->{Map<String,Object> row=one("SELECT payment.id,payment.order_id,payment.status,payment.reconciliation_attempts,orders.member_id FROM payments payment JOIN orders ON orders.id=payment.order_id WHERE payment.id=? FOR UPDATE",id);if(!"UNKNOWN".equals(row.get("status")))return view(id);if("SUCCEEDED".equals(result.status())){long orderId=((Number)row.get("order_id")).longValue();for(Map<String,Object> item:jdbc.queryForList("SELECT sku_id,quantity FROM order_items WHERE order_id=?",orderId)){long sku=((Number)item.get("sku_id")).longValue();int q=((Number)item.get("quantity")).intValue();jdbc.update("UPDATE inventories SET reserved_quantity=reserved_quantity-?,version=version+1 WHERE sku_id=?",q,sku);jdbc.update("INSERT INTO inventory_movements(sku_id,payment_id,type,quantity,available_before,available_after,reserved_before,reserved_after,created_at) SELECT ?,?,'DEDUCT',?,available_quantity,available_quantity,reserved_quantity,reserved_quantity-?,? FROM inventories WHERE sku_id=?",sku,id,q,q,Timestamp.from(Instant.now()),sku);}jdbc.update("UPDATE payments SET status='SUCCEEDED',provider_status='DONE',approved_at=? WHERE id=?",Timestamp.from(Instant.now()),id);jdbc.update("UPDATE orders SET status='PAID',paid_at=? WHERE id=?",Timestamp.from(Instant.now()),orderId);jdbc.update("INSERT INTO deliveries(order_id,status) VALUES (?,'PREPARING') ON DUPLICATE KEY UPDATE id=id",orderId);notifications.create(((Number)row.get("member_id")).longValue(),"ORDER_PAID","ORDER",orderId);}else if(((Number)row.get("reconciliation_attempts")).intValue()>=10){jdbc.update("UPDATE orders SET status='PAYMENT_ACTION_REQUIRED' WHERE id=?",row.get("order_id"));notifications.create(((Number)row.get("member_id")).longValue(),"PAYMENT_ACTION_REQUIRED","PAYMENT",id);}return view(id);});}
	private Map<String,Object> view(long id){return one("SELECT id AS paymentId,order_id AS orderId,status,reconciliation_attempts AS reconciliationAttempts,last_reconciled_at AS lastReconciledAt FROM payments WHERE id=?",id);}private Map<String,Object> one(String sql,Object...args){var rows=jdbc.queryForList(sql,args);return rows.isEmpty()?null:new LinkedHashMap<>(rows.getFirst());}
}
