"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ErrorState, LoadingState } from "@/components/async-state";
import { ApiError } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";
import { buildLoginHref, formatPrice } from "@/lib/frontend-utils";
import { commerceFinalApi, type CartItem } from "@/lib/commerce-final-api";
export default function CartPage() { const auth=useAuth(); const [items,setItems]=useState<CartItem[]|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState<number|null>(null); const [draftQuantities,setDraftQuantities]=useState<Record<number,string>>({}); const [quantityErrors,setQuantityErrors]=useState<Record<number,string>>({}); const load=()=>{void commerceFinalApi.cart().then(r=>{setItems(r.items);setDraftQuantities(Object.fromEntries(r.items.map(item=>[item.skuId,String(item.quantity)])));setError(null);}).catch((e:unknown)=>{if(e instanceof ApiError&&e.code==="AUTH_REQUIRED"){auth.markAnonymous();return;}setError(e instanceof ApiError?e.message:"장바구니를 불러오지 못했습니다.");});};useEffect(()=>{if(auth.status==="authenticated")load();},[auth.status]); const change=(item:CartItem,raw:string)=>{setDraftQuantities(current=>({...current,[item.skuId]:raw}));const quantity=Number(raw);if(!Number.isInteger(quantity)||quantity<1){setQuantityErrors(current=>({...current,[item.skuId]:"수량은 1 이상의 정수여야 합니다."}));return;}setQuantityErrors(current=>{const next={...current};delete next[item.skuId];return next;});setBusy(item.skuId);void auth.executeWithCsrf(csrf=>commerceFinalApi.updateCart(item.skuId,quantity,csrf)).then(load).catch((e:unknown)=>setError(e instanceof ApiError?e.message:"수량을 변경하지 못했습니다.")).finally(()=>setBusy(null));};if(auth.status==="anonymous")return <ErrorState title="로그인이 필요합니다." message="장바구니를 보려면 로그인해 주세요."><Link className="button button-primary" href={buildLoginHref("/cart")}>로그인</Link></ErrorState>;if(auth.status==="error")return <ErrorState title="로그인 상태를 확인할 수 없습니다." message={auth.errorMessage??"다시 시도해 주세요."} onRetry={()=>void auth.refresh()}/>;if(items===null&&!error)return <LoadingState>장바구니를 불러오고 있습니다.</LoadingState>;if(error)return <ErrorState title="장바구니를 불러오지 못했습니다." message={error} onRetry={load}/>;return <section className="section-card"><h1>장바구니</h1>{items?.length?<><ul className="history-list">{items.map(item=><li key={item.skuId}><strong>{item.productName}</strong><span>{item.skuName} · {formatPrice(item.price)}</span><label>수량 <input className="input" type="number" min="1" value={draftQuantities[item.skuId]??String(item.quantity)} disabled={busy===item.skuId} onChange={e=>change(item,e.target.value)}/></label>{quantityErrors[item.skuId]?<p className="field-error" role="alert">{quantityErrors[item.skuId]}</p>:null}<button className="button button-secondary" type="button" disabled={busy===item.skuId} onClick={()=>{setBusy(item.skuId);void auth.executeWithCsrf(csrf=>commerceFinalApi.deleteCart(item.skuId,csrf)).then(load).catch((e:unknown)=>setError(e instanceof ApiError?e.message:"삭제하지 못했습니다.")).finally(()=>setBusy(null));}}>삭제</button></li>)}</ul><Link className="button button-primary" href="/checkout">주문하기</Link></>:<p>장바구니가 비어 있습니다.</p>}</section>; }
